name: publish
on: 
  #push:
  #  branches: [ main ]

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the nginx Docker image
        run: |
          docker build . --tag ghcr.io/koenraadva/hello-world-nginx:v02
          docker push ghcr.io/koenraadva/hello-world-nginx:v02